### ISSUE TITLE
请教下原理, 相邻两个请求的码是连续的

### ISSUE THREAD

**Issue by bigdong89** [wrfly/yasuser#23]
原理是xxhash xxhash.ChecksumString64　?
然后相邻请求的hash是连续的，怎么才能防范对url的攻击呢？
正式点叫hash flooding
比如/a1, /a2, /a3, ...
这样遍历可以请求到我们所有的资源，但是我们是不希望对方进行暴力爬取的。

**Comment by wrfly** [comment]
emmm 别的短域名也是连续的，如果想针对暴力爬取的话：
一是可以限制单IP的访问次数：这样不能防止别人换IP爬
二是可以在每个生成的hash上加一个随机数字：这样复杂一点，需要防止碰撞，同时也牺牲了“短”这个特性
三是在二的基础上优化，比如在前面加一个随机数字，范围可以是`[00, ZZ]`：这样不用防止碰撞，比如`a5x6`,对数据库而言其实是`x6`，但对于爬虫而言，他不知道到底是`a5`还是`b3`

在三的基础上，还可以在中间加两位部署序号，比如 `a5D3x6`，混淆数字是`a5`，部署节点是`D3`，这样请求过来去`D3`查找`x6`即可，同时每个实例的DB也都是独立的，提高了性能。

---

以上拙见，如有纰漏还请不吝赐教。

**Comment by bigdong89** [comment]
对于系统设计的正确性的疑问
此库的demo版本生成的url总是两位的。
即使假设每位（２６个英文×２大小写　＋　１０）＝　62, 　共有62*62=3844的地址，
您的demo上线这么久，为什么还没突破这个限制到三位呢？
关键问题是用checksum作结果是错误的！

建议阅读下checksum的定义　https://baike.baidu.com/item/%E6%A0%A1%E9%AA%8C%E5%92%8C

附python版的xxhash
>>> import xxhash
>>> xxhash.VERSION
'1.4.3'
>>> xxhash.xxh32('http://www.baidu.com/1234?a=12312313123&f2r12233').hexdigest()
'1575b90b'
>>> xxhash.xxh32('http://www.baidu.com/1234?a=12312313123&f2r12234').hexdigest()
'39ee2f54'


可以考虑改进的地方
1.　采用xxhash.ChecksumString64s(longString, seed)增加seed参数，可以采用不一样的seed, 这样所有人生成的短码是不一样的。
２．checksum连续的问题，应该跟hash设计的原理有关。建议不取checksum而直接取hash结果，但只取６－７位，碰撞的概率应该会更低。另外hash后的结果是不区分大小写的，可通过用62进制重新编码来继续缩短位数。

**Comment by bigdong89** [comment]
此外这个版本代码上生产环境的建议：
１．long2short url的接口没有进行授权验证，无法私有使用。
２．几个参数都是写到headers里，这样是否是必要的。

作者的思路，目前的代码设计都是很好的。
有空再修改提交，再次谢过作者的工作。

**Comment by wrfly** [comment]
emmmm

没有突破三位纯粹是没人用而已，现在DB里只有400+的URL，首页有展示的

相邻的请求是连续的，这个问题其实我并没有特别关注，别人想攻击就攻击呗，如果想保证是私密的，可以用`custom`的short URL，这个custom也相当于密码了

写到header里的话，因为一开始是没有前端页面的，写这个小东西的初衷也是没找到短域名服务的API，大家都是页面，而我很喜欢命令行，所以想短域名这个事儿也通过命令行做了，就放header里了，图省事儿

然后，这个程序并不是通过checksum来确定短码的，而是将checksum的结果作为一个索引，也避免了提交重复的URL而得到不同的结果，因为URL的checksum是一致的，程序内部有个累加器，来一个加一个，所以才会变短。其实最简单的方法就是用checksum或者md5就好了，但是这样还是很长，虽然满足了不能被遍历的这个条件，但是这个程序是短域名服务，主要目的在于短

最后，感谢你对这个小玩意儿的关注，这东西是一年多前写的，里面的代码啊注释啊逻辑啊结构啊命名啊都不太好，纯粹是个只能work的玩意儿，没啥特别之处，写这个的另一个动机是太闲，找点事情做……

至于上生产的话，还差得很远，至少DB就有问题，高并发也是个笑话LOL，也没个监控和统计，代码也是乱七八糟的……

再次谢过你的关注和Star。

**Comment by bigdong89** [comment]
仔细看了下代码，确实是keyNum, err := s.db.IncKey()来自增的，
搞错了抱歉，多谢回复。
